apiVersion: v1
kind: Service
metadata:
  name: reg-service-deployment-lb-svc-yaml
  labels:
    app: backend-reg-service
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: backend-reg-service
  ports:
    - name: http
      port: 80
      targetPort: 8081
