apiVersion: apps/v1
kind: Deployment
metadata:
  name: eprescription-demo-ui-deployment
  labels:
    app: eprescription-demo-ui
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eprescription-demo-ui
  template:
    metadata:
      labels:
        app: eprescription-demo-ui
        tier: backend
    spec:
      containers:
        - name: eprescription-demo-ui
          image: dockersubrata/eprescription-demo-ui-image:2.0
          ports:
            - containerPort: 8081

