apiVersion: v1
kind: Service
metadata:
  name: eprescription-demo-ui-deployment-lb-svc
  labels:
    app: eprescription-demo-ui
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: eprescription-demo-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
