apiVersion: apps/v1
kind: Deployment
metadata:
  name: reg-service-deployment-dynamo
  labels:
    app: backend-reg-service-dynamo
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-reg-service-dynamo
  template:
    metadata:
      labels:
        app: backend-reg-service-dynamo
        tier: backend
    spec:
      serviceAccountName: reg-service-dynamo-sa
      containers:
        - name: backend-reg-service-dynamo
          image: dockersubrata/eprescription-reg-service-image:7.0
          ports:
            - containerPort: 8081

